<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>nh_patchproj</RootNamespace>
    <AssemblyName>nh_patchproj</AssemblyName>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>nh_patchproj</ToolCommandName>
    <Version>1.0.0</Version>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <NoWarn>$(NoWarn);NU3018;NU3028;NU3037;NU3042</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="17.3.2" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.6.10" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources/readme.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
