#!/usr/bin/perl

=encoding UTF-8

=head1 NAME

dh_installnuget - install NuGet packages

=head1 SYNOPSIS

B<dh_installnuget> [S<I<debhelper options>>] [B<--nuget-path=>I<path>]

=head1 DESCRIPTION

B<dh_installnuget> installs NuGet packages to system-wide locations.

By default, packages are installed to F</usr/lib/nuget/>.
Use B<--nuget-path> to specify a custom installation path.

=head1 FILES

=over 4

=item debian/I<package>.nuget debian/nuget

Lists the NuGet packages to be installed per package. Each line in that file
should be of the form C<I<path>>, where I<path> indicates where the NuGet
package resides in the source tree.

=back

=head1 OPTIONS

=over 4

=item B<--nuget-path=>I<path>

Set the base installation path. Can be specified only once.
When used, the default path is B<not> used.

Default (when no --nuget-path specified): F</usr/lib/nuget/>

Example:
  --nuget-path=/usr/share/nuget

=back

=head1 NOTES

Note that this command is not idempotent. L<dh_prep(1)> should be called
between invocations of this command. Otherwise, it may cause multiple
instances of the same text to be added to maintainer scripts.

When using custom paths (especially F</usr/local>), be aware that this may
violate Debian Policy and could cause issues with package management. Consider
using standard paths like F</usr/share> or F</usr/lib> for official packages.

=head1 SEE ALSO

L<debhelper(7)>

This program is not a part of debhelper.

=head1 AUTHORS

Наследов Дмитрий <dnasledov@lab50.net>

Шлыков Василий <vash@lab50.net>

=cut

use strict;
use warnings;
use Debian::Debhelper::Dh_Lib;
use Digest::SHA qw(sha512_base64 sha256_base64);
use Archive::Zip qw(:ERROR_CODES);
use Archive::Extract;
use XML::LibXML;
use File::Basename;

my $default_path = '/usr/lib/nuget';

my $nuget_path;

init(options => {
    'nuget-path=s'  => \$nuget_path,
});

$nuget_path = $default_path unless $nuget_path;

# Нормализация пути (убираем leading и trailing slash)
$nuget_path =~ s/^\/+//;
$nuget_path =~ s/\/+$//;

verbose_print("Installation path: $nuget_path") if $dh{V};

if (-e 'debian/nuget' or glob('debian/*.nuget')) {
    # Если заданы файлы, работаем по ним
    foreach my $package (@{$dh{DOPACKAGES}}) {
        my $nugetlistfile = pkgfile(
            {
                'named'                            => 1,
                'support-architecture-restriction' => 0
            },
            $package,
            'nuget'
        );

        next unless $nugetlistfile;

        open(my $fd, '<:encoding(utf8)', $nugetlistfile)
            or error("open $nugetlistfile failed: $!");

        while (my $nugetfile = <$fd>) {
            chomp $nugetfile;
            next if $nugetfile =~ /^\s*($|#)/;

            error("package $nugetfile not exists") unless -f $nugetfile;

            install_nuget($package, $nugetfile);
        }
        close $fd;
    }
} else {
    # Иначе попытаемся просто распаковать все .nupkg
    foreach my $package (@{$dh{DOPACKAGES}}) {
        my $tmp = tmpdir($package);
        next unless -d $tmp;

        my @nupkgs = glob($tmp . '/' . $nuget_path . '/*.nupkg');
        foreach my $nupkg (@nupkgs) {
                install_nuget($package, $nupkg);
                rm_files($nupkg);
        }
    }
}

sub install_nuget {
    my $package = shift;
    my $nugetfile = shift;

    print("\tInstalling $nugetfile\n");

    my ($id, $version) = get_nuget_metadata($nugetfile, $package);
    verbose_print("$nugetfile $id ($version)") if $dh{V};
    
    my $tmpdir = tmpdir($package);
    # Добавлен разделитель / между $tmpdir и $nuget_path
    my $fulldest = "$tmpdir/$nuget_path/" . lc($id) . "/" . lc($version);

    install_dir($fulldest) unless -d $fulldest;

    verbose_print("extracting $nugetfile to $fulldest");
    my $archive = Archive::Extract->new(archive => $nugetfile, type => 'zip');
    $archive->extract(to => $fulldest) or error("error opening archive $nugetfile");

    my $checksumfile = $fulldest . '/' . lc(basename($nugetfile)) . '.sha512';
    verbose_print("generating $checksumfile");
    open(my $fh, '>', $checksumfile) or error("failed to write to $checksumfile");
    print {$fh} sha512_base64($nugetfile);
    close($fh) or error("closing $checksumfile: $!");

    my $metadatafile = "$fulldest/.nupkg.metadata";
    verbose_print("generating $metadatafile");
    my $checksum = sha256_base64($nugetfile);
    open($fh, '>', $metadatafile) or error("failed to write to $metadatafile");
    print {$fh} << "JSON";
{
"version": 2,
"contentHash": "$checksum"
}
JSON
    close($fh) or error("closing $metadatafile: $!");
}

sub get_nuget_metadata {
    my ($nugetfile, $package) = @_;

    my $zip = Archive::Zip->new();
    $zip->read($nugetfile) == AZ_OK or error("$nugetfile read failed: $!");

    my ($nuspec) = grep { m{^[^/]+\.nuspec$}i } $zip->memberNames();
    if ($nuspec) {
        my $content = $zip->memberNamed($nuspec)->contents();
        my $doc = XML::LibXML->new()->parse_string($content);
        my $root = $doc->documentElement();

        my ($id_node) = $root->findnodes('.//*[local-name()="metadata"]/*[local-name()="id"]');
        my ($ver_node) = $root->findnodes('.//*[local-name()="metadata"]/*[local-name()="version"]');

        my $id = $id_node ? clean_text($id_node->textContent()) : undef;
        my $ver = $ver_node ? clean_text($ver_node->textContent()) : undef;
        
        return ($id, $ver);
    } else {
        error(".nuspec file not found in $nugetfile");
    }
}

sub clean_text {
    my $text = shift;
    $text =~ s/^\s+|\s+$//g;
    return $text;
}
